"""Update user_image_id type to Integer

Revision ID: 0842ada7b0ae
Revises: cb769b3b00db
Create Date: 2024-11-05 18:03:08.310931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0842ada7b0ae'
down_revision = 'cb769b3b00db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image_tags', schema=None) as batch_op:
        batch_op.alter_column('user_image_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image_tags', schema=None) as batch_op:
        batch_op.alter_column('user_image_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
